# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: reservaia
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: reservaia-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: reservaia-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  environment:
    THREADS_TABLE: Threads
    BUSINESSES_TABLE: Businesses
    GOOGLE_SERVICE_ACCOUNT_SECRET: GoogleServiceAccountCredentials
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:us-east-2:*:table/Threads
        - arn:aws:dynamodb:us-east-2:*:table/Businesses
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: 
        - arn:aws:secretsmanager:us-east-2:*:secret:GoogleServiceAccountCredentials-*

functions:
  webhook:
    handler: handler.webhook
    timeout: 30
    events:
      - httpApi:
          path: /
          method: post

resources:
  Resources:
    ThreadsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Threads
        AttributeDefinitions:
          - AttributeName: to
            AttributeType: S
          - AttributeName: from
            AttributeType: S
        KeySchema:
          - AttributeName: to
            KeyType: HASH
          - AttributeName: from
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    BusinessesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Businesses
        AttributeDefinitions:
          - AttributeName: phonenumber
            AttributeType: S
        KeySchema:
          - AttributeName: phonenumber
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    GoogleServiceAccountCredentials:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: GoogleServiceAccountCredentials
        Description: "Stores Google Service Account credentials for authentication"
